# Generated by Django 5.2.7 on 2025-10-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to-do", "To Do"),
                    ("in-progress", "In Progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                ],
                default="to-do",
                max_length=20,
            ),
        ),
    ]
