# Generated by Django 5.2.7 on 2025-10-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(default="medium", max_length=20),
        ),
    ]
