# Generated by Django 5.2.7 on 2025-10-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0003_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
